# Text classifier


- Applying Yelp reviews data
- part of course assignment

## Task 1

Read **`yelp.csv`** into a Pandas DataFrame and examine it.

### Importing key Modules

In [1]:
# for Python 2: use print only as a function
from __future__ import print_function

In [2]:
# read yelp.csv using a relative path
import pandas as pd
path = '../data/yelp.csv'
df = pd.read_csv(path)

In [3]:
df.shape

(10000, 10)

In [4]:
df.head()

business_id        date               review_id  stars  \
0  9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1  ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
2  6oRAC4uyJCsJl1X0WZpVSA  2012-06-14  IESLBzqUCLdSzSqm0eCSxQ      4   
3  _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4  6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   

                                                text    type  \
0  My wife took me here on my birthday for breakf...  review   
1  I have no idea why some people give bad review...  review   
2  love the gyro plate. Rice is so good and I als...  review   
3  Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4  General Manager Scott Petello is a good egg!!!...  review   

                  user_id  cool  useful  funny  
0  rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1  0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
2  0hT2KtfLiobPvh6cDC8JQg     0       1      0  
3  uZetl9T0NcROGOyFfughhg     1       2      0  
4  vYmM4KTsC8ZfQBg-j5MWkw     0       0      0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
business_id    10000 non-null object
date           10000 non-null object
review_id      10000 non-null object
stars          10000 non-null int64
text           10000 non-null object
type           10000 non-null object
user_id        10000 non-null object
cool           10000 non-null int64
useful         10000 non-null int64
funny          10000 non-null int64
dtypes: int64(4), object(6)
memory usage: 781.4+ KB


## Task 2

Create a new DataFrame that only contains the **5-star** and **1-star** reviews.

- **Hint:** [How do I apply multiple filter criteria to a pandas DataFrame?](https://www.youtube.com/watch?v=YPItfQ87qjM&list=PL5-da3qGB5ICCsgW1MxlZ0Hq8LL5U3u9y&index=9) explains how to do this.

### using pandas filter criteria

In [6]:
df[df.stars==1]

business_id        date               review_id  stars  \
23    IJ0o6b8bJFAbG6MjGfBebQ  2010-09-05  Dx9sfFU6Zn0GYOckijom-g      1   
31    vvA3fbps4F9nGlAEYKk_sA  2012-05-04  S9OVpXat8k5YwWCn6FAgXg      1   
35    o1GIYYZJjM6nM03fQs_uEQ  2011-11-30  ApKbwpYJdnhhgP4NbjQw2Q      1   
61    l4vBbCL9QbGiwLuLKwD_bA  2011-11-22  DJVxOfj2Rw9zklC9tU3i1w      1   
64    CEswyP-9SsXRNLR9fFGKKw  2012-05-19  GXj4PNAi095-q9ynPYH3kg      1   
...                      ...         ...                     ...    ...   
9924  mhQCxOiqp03qnhGRTtPduw  2012-07-07  PCjnn__E8AzNa2kXFXxTHQ      1   
9931  C_eWAEOvkHZ_IZYGwjtpmg  2011-04-25  QfdoE-XqEeCsttJH8g0ugQ      1   
9953  QCxXYA13PtkD3wec47_r8Q  2012-03-14  V2N2TCqnaqMYfg7zXGG-Rg      1   
9984  wepFVY82q_tuDzG6lQjHWw  2012-02-12  spusZYROtBKw_5tv3gYm4Q      1   
9987  r-a-Cn9hxdEnYTtVTB5bMQ  2012-04-07  j9HwZZoBBmJgOlqDSuJcxg      1   

                                                   text    type  \
23    U can go there n check the car out. If u wanna...  review   
31    Disgusting!  Had a Groupon so my daughter and ...  review   
35    I've eaten here many times, but none as bad as...  review   
61    I have always been a fan of Burlington's deals...  review   
64    Another night meeting friends here.  I have to...  review   
...                                                 ...     ...   
9924                                  Horrible service.  review   
9931  I love Saddle Ranch for its casual night time ...  review   
9953  "Hipster,Trendy" ????-I think NOT !!!! Very di...  review   
9984  Went last night to Whore Foods to get basics t...  review   
9987  The food is delicious.  The service:  discrimi...  review   

                     user_id  cool  useful  funny  
23    zRlQEDYd_HKp0VS3hnAffA     0       1      1  
31    8AMn6644NmBf96xGO3w6OA     0       1      0  
35    iwUN95LIaEr75TZE_JC6bg     0       4      3  
61    EPROVap0M19Y6_4uf3eCmQ     0       0      0  
64    MjLAe48XNfYlTeFYca5gMw     0       1      2  
...                      ...   ...     ...    ...  
9924  rvaJcf5OIY2So_pkoqDHLQ     0       1      0  
9931  yhGfcKunPjcy-v-1ppr6oQ     0       2      0  
9953  JEQ6el2-tLtKJU6k_SpE-w     0       2      0  
9984  W7zmm1uzlyUkEqpSG7PlBw     0       1      2  
9987  toPtsUtYoRB-5-ThrOy2Fg     0       0      0  

[749 rows x 10 columns]

In [7]:
len(df[df.stars==1])

749

In [8]:
df[df.stars==5]

business_id        date               review_id  stars  \
0     9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1     ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
3     _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4     6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   
6     zp713qNhx8d9KCJJnrw1xA  2010-02-12  riFQ3vxNpP4rWLk_CSri2A      5   
...                      ...         ...                     ...    ...   
9990  R8VwdLyvsp9iybNqRvm94g  2011-10-03  pcEeHdAJPoFNF23es0kKWg      5   
9991  WJ5mq4EiWYAA4Vif0xDfdg  2011-12-05  EuHX-39FR7tyyG1ElvN1Jw      5   
9992  f96lWMIAUhYIYy9gOktivQ  2009-03-10  YF17z7HWlMj6aezZc-pVEw      5   
9994  L3BSpFvxcNf3T_teitgt6A  2012-03-19  0nxb1gIGFgk3WbC5zwhKZg      5   
9999  pF7uRzygyZsltbmVpjIyvw  2010-10-16  vWSmOhg2ID1MNZHaWapGbA      5   

                                                   text    type  \
0     My wife took me here on my birthday for breakf...  review   
1     I have no idea why some people give bad review...  review   
3     Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4     General Manager Scott Petello is a good egg!!!...  review   
6     Drop what you're doing and drive here. After I...  review   
...                                                 ...     ...   
9990  Yes I do rock the hipster joints.  I dig this ...  review   
9991  Only 4 stars? \n\n(A few notes: The folks that...  review   
9992  I'm not normally one to jump at reviewing a ch...  review   
9994  Let's see...what is there NOT to like about Su...  review   
9999  4-5 locations.. all 4.5 star average.. I think...  review   

                     user_id  cool  useful  funny  
0     rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1     0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
3     uZetl9T0NcROGOyFfughhg     1       2      0  
4     vYmM4KTsC8ZfQBg-j5MWkw     0       0      0  
6     wFweIWhv2fREZV_dYkz_1g     7       7      4  
...                      ...   ...     ...    ...  
9990  b92Y3tyWTQQZ5FLifex62Q     1       1      1  
9991  hTau-iNZFwoNsPCaiIUTEA     1       1      0  
9992  W_QXYA7A0IhMrvbckz7eVg     2       3      2  
9994  OzOZv-Knlw3oz9K5Kh5S6A     1       2      1  
9999  KSBFytcdjPKZgXKQnYQdkA     0       0      0  

[3337 rows x 10 columns]

In [9]:
len(df[df.stars==5])

3337

In [10]:
df[(df.stars==1) | (df.stars==5)]

business_id        date               review_id  stars  \
0     9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1     ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
3     _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4     6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   
6     zp713qNhx8d9KCJJnrw1xA  2010-02-12  riFQ3vxNpP4rWLk_CSri2A      5   
...                      ...         ...                     ...    ...   
9990  R8VwdLyvsp9iybNqRvm94g  2011-10-03  pcEeHdAJPoFNF23es0kKWg      5   
9991  WJ5mq4EiWYAA4Vif0xDfdg  2011-12-05  EuHX-39FR7tyyG1ElvN1Jw      5   
9992  f96lWMIAUhYIYy9gOktivQ  2009-03-10  YF17z7HWlMj6aezZc-pVEw      5   
9994  L3BSpFvxcNf3T_teitgt6A  2012-03-19  0nxb1gIGFgk3WbC5zwhKZg      5   
9999  pF7uRzygyZsltbmVpjIyvw  2010-10-16  vWSmOhg2ID1MNZHaWapGbA      5   

                                                   text    type  \
0     My wife took me here on my birthday for breakf...  review   
1     I have no idea why some people give bad review...  review   
3     Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4     General Manager Scott Petello is a good egg!!!...  review   
6     Drop what you're doing and drive here. After I...  review   
...                                                 ...     ...   
9990  Yes I do rock the hipster joints.  I dig this ...  review   
9991  Only 4 stars? \n\n(A few notes: The folks that...  review   
9992  I'm not normally one to jump at reviewing a ch...  review   
9994  Let's see...what is there NOT to like about Su...  review   
9999  4-5 locations.. all 4.5 star average.. I think...  review   

                     user_id  cool  useful  funny  
0     rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1     0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
3     uZetl9T0NcROGOyFfughhg     1       2      0  
4     vYmM4KTsC8ZfQBg-j5MWkw     0       0      0  
6     wFweIWhv2fREZV_dYkz_1g     7       7      4  
...                      ...   ...     ...    ...  
9990  b92Y3tyWTQQZ5FLifex62Q     1       1      1  
9991  hTau-iNZFwoNsPCaiIUTEA     1       1      0  
9992  W_QXYA7A0IhMrvbckz7eVg     2       3      2  
9994  OzOZv-Knlw3oz9K5Kh5S6A     1       2      1  
9999  KSBFytcdjPKZgXKQnYQdkA     0       0      0  

[4086 rows x 10 columns]

In [11]:
df_star=df[(df.stars==1) | (df.stars==5)]

In [12]:
df_star.shape

(4086, 10)

In [13]:
df_star.stars.value_counts()

5    3337
1     749
Name: stars, dtype: int64

## Task 3

Define X and y from the new DataFrame, and then split X and y into training and testing sets, using the **review text** as the only feature and the **star rating** as the response.

- **Hint:** Keep in mind that X should be a Pandas Series (not a DataFrame), since we will pass it to CountVectorizer in the task that follows.

In [14]:
X=df_star.text
y=df_star.stars

In [15]:
print(X.shape)
print(y.shape)

(4086,)
(4086,)


In [16]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2020)
print(X_train.shape)
print(X_test.shape)

(3064,)
(1022,)


## Task 4

Use CountVectorizer to create **document-term matrices** from X_train and X_test.

In [17]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
# instantiate the vectorizer
vect = CountVectorizer()

### a.Applying CountVectorizer on training data

In [18]:
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [19]:
# examine the fitted vocabulary
tokens=vect.get_feature_names()
tokens[:10]

['00', '000', '00a', '00am', '00pm', '01', '02', '03', '03342', '04']

In [20]:
tokens[-10:]

['zuccini',
 'zuchinni',
 'zumba',
 'zupa',
 'zupas',
 'zuzu',
 'zuzus',
 'zwiebel',
 'école',
 'ém']

In [21]:
# transforming training data to document term matrix
X_train_dtm = vect.transform(X_train)

In [22]:
# examine the document-term matrix
X_train_dtm

<3064x16867 sparse matrix of type '<class 'numpy.int64'>'
	with 235839 stored elements in Compressed Sparse Row format>

In [23]:
type(X_train_dtm)

scipy.sparse.csr.csr_matrix

In [24]:
# convert to array
X_train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [25]:
ngram=pd.DataFrame(X_train_dtm.toarray(), columns=vect.get_feature_names())
ngram.shape

(3064, 16867)

In [26]:
ngram.head()

00  000  00a  00am  00pm  01  02  03  03342  04  ...  zuccini  zuchinni  \
0   0    0    0     0     0   0   0   0      0   0  ...        0         0   
1   0    0    0     0     0   0   0   0      0   0  ...        0         0   
2   0    0    0     0     0   0   0   0      0   0  ...        0         0   
3   0    1    0     0     0   0   0   0      0   0  ...        0         0   
4   0    0    0     0     0   0   0   0      0   0  ...        0         0   

   zumba  zupa  zupas  zuzu  zuzus  zwiebel  école  ém  
0      0     0      0     0      0        0      0   0  
1      0     0      0     0      0        0      0   0  
2      0     0      0     0      0        0      0   0  
3      0     0      0     0      0        0      0   0  
4      0     0      0     0      0        0      0   0  

[5 rows x 16867 columns]

### b.transforming test set

In [27]:
# only using transform , not fit
X_test_dtm = vect.transform(X_test)
X_test_dtm

<1022x16867 sparse matrix of type '<class 'numpy.int64'>'
	with 78901 stored elements in Compressed Sparse Row format>

## Task 5

Use Multinomial Naive Bayes to **predict the star rating** for the reviews in the testing set, and then **calculate the accuracy** and **print the confusion matrix**.

- **Hint:** [Evaluating a classification model](https://github.com/justmarkham/scikit-learn-videos/blob/master/09_classification_metrics.ipynb) explains how to interpret both classification accuracy and the confusion matrix.

### a)- Buidling Naive Bayes model

In [28]:
# import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [29]:
# train the model using X_train_dtm 
%time nb.fit(X_train_dtm, y_train)

CPU times: user 4.99 ms, sys: 1.4 ms, total: 6.4 ms
Wall time: 4.7 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [30]:
# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)
y_pred_class[:5]

array([5, 1, 5, 5, 5])

### b.calculate accuracy 

In [31]:
# calculate accuracy of class predictions. This is for 5 stars reviews
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.9275929549902152

### c.confusion matrix

In [32]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[128,  58],
       [ 16, 820]])

## Task 6 (Challenge)

Calculate the **null accuracy**, which is the classification accuracy that could be achieved by always predicting the most frequent class.

- **Hint:** [Evaluating a classification model](https://github.com/justmarkham/scikit-learn-videos/blob/master/09_classification_metrics.ipynb) explains null accuracy and demonstrates two ways to calculate it, though only one of those ways will work in this case. Alternatively, you can come up with your own method to calculate null accuracy!

In [33]:
y_test.value_counts()

5    836
1    186
Name: stars, dtype: int64

In [34]:
# for null accuracy for 5-star reveiws
y_test.value_counts().head(1) / len(y_test)

5    0.818004
Name: stars, dtype: float64

In [35]:
# calculate null accuracy manually
836 / float(836 + 186)

0.8180039138943248

## Task 7 (Challenge)

Browse through the review text of some of the **false positives** and **false negatives**. Based on your knowledge of how Naive Bayes works, do you have any ideas about why the model is incorrectly classifying these reviews?

- **Hint:** [Evaluating a classification model](https://github.com/justmarkham/scikit-learn-videos/blob/master/09_classification_metrics.ipynb) explains the definitions of "false positives" and "false negatives".
- **Hint:** Think about what a false positive means in this context, and what a false negative means in this context. What has scikit-learn defined as the "positive class"?

In [36]:
X_test.shape

(1022,)

In [37]:
y_test.shape

(1022,)

In [38]:
y_pred_class.shape

(1022,)

### false positives samples

In [39]:
# print message text for the false positives (meaning they were incorrectly classified as 5 stars)
X_test[y_test < y_pred_class]

7994    This place is pure crap! The players are sub-p...
8514                                      Out of business
89      I was really excited about this event, maybe m...
3469    "The office space, layout, presentation gets 5...
3677    Hands down, the single worst public mass trans...
1704    The only reason 1 star can be given is the fla...
3715    The cheesy breadsticks were delicious.  Everyt...
7956    What was Dunkin Donuts thinking when they took...
8000    Still a place that is unacceptable in my book-...
7382    Thank you to Sarah L for bringing to my attent...
1919                                         D-scust-ing.
8362    Some of my friends brought me here last night ...
1418    So, what kind of place serves chicken fingers ...
4643    ok so here's what they teach:  if you are a go...
7380    I keep wanting to like this place.  I want to ...
9272    I enjoy falafels and my boyfriend really likes...
113     Unless you are a regular or look like your wal...
2175    This h

### false negatives samples

In [40]:
# print message text for the false negatives (meaning they were incorrectly classified as 1-star)
X_test[y_test > y_pred_class]

8083    After unsuccessfully attempting a walk in gel ...
696     This is the only auto repair place I've ever s...
3052    When I met some friends for dinner at this res...
2306    There are certain people in your life that you...
6637    no chip manicure: no drilling, no filing, no d...
5637    I'm giving them a 5 star review for how they h...
402     Once again Wildflower proves why it's my favor...
763     Here's the deal. I said I was done with OT, bu...
1169    I have been taking vehicles to this place for ...
6512    When my youngest son graduated I took him to B...
3999    TJ was there for me when my water heater broke...
1456    What happened to this place?  The food was goo...
7148    I now consider myself an Arizonian. If you dri...
7300    Decided to call CityWide based on positive onl...
1341    Just want to Say ThankYou Hawaiian Airlines fo...
6318    Since I have ranted recently on poor customer ...
Name: text, dtype: object

In [41]:
X_test[763]

"Here's the deal. I said I was done with OT, but a friend told me the management had changed and it was worth another shot. \n\nMy friend was right.\n\nEverything I had a problem with before was remedied. I went in unannounced, didn't tell anyone about a previous bad experience, and I was given some of the best service I've received in town. When we went in, we were sat quickly and tended to very well for our entire visit.\n\nNo texting employees, no indifferent waitstaff. The chef was in the food window expediting food, making sure it went out promptly and correctly. Not only was our server attentive, but there was a team service atmosphere and other servers came by our table when we had empty drinks, debris on the table, etc. \n\nThe decor has been refreshed, and although I didn't dislike the decor originally, it is definitely an upgrade as well. Now its much cleaner, but still maintains the character that was part of its charm before. \n\nProps to the new management. Well done. I'll

## Task 8 (Challenge)

Calculate which 10 tokens are the most predictive of **5-star reviews**, and which 10 tokens are the most predictive of **1-star reviews**.

- **Hint:** Naive Bayes automatically counts the number of times each token appears in each class, as well as the number of observations in each class. You can access these counts via the `feature_count_` and `class_count_` attributes of the Naive Bayes model object.

In [42]:
# store the vocabulary of X_train
X_train_tokens = vect.get_feature_names()
len(X_train_tokens)

16867

In [43]:
print(X_train_tokens[0:50])

['00', '000', '00a', '00am', '00pm', '01', '02', '03', '03342', '04', '05', '06', '07', '09', '0buxoc0crqjpvkezo3bqog', '0l', '10', '100', '1000', '1000x', '1001', '100s', '100th', '101', '1030', '105', '1070', '108', '10am', '10ish', '10min', '10mins', '10minutes', '10pm', '10th', '10x', '10yo', '11', '110', '1100', '111', '111th', '112', '116', '11a', '11am', '11p', '11pm', '12', '120']


In [44]:
print(X_train_tokens[-50:])

['zabba', 'zach', 'zam', 'zanella', 'zankou', 'zappos', 'zatsiki', 'zen', 'zero', 'zest', 'zesty', 'zha', 'zhou', 'zia', 'zichini', 'zihuatenejo', 'zillion', 'zin', 'zinburger', 'zinburgergeist', 'zinc', 'zinfandel', 'zing', 'zip', 'zipcar', 'ziploc', 'zipper', 'zippers', 'zipps', 'ziti', 'zoe', 'zombi', 'zombies', 'zone', 'zoning', 'zoo', 'zoom', 'zoyo', 'zucca', 'zucchini', 'zuccini', 'zuchinni', 'zumba', 'zupa', 'zupas', 'zuzu', 'zuzus', 'zwiebel', 'école', 'ém']


### using model to count tokens

In [45]:
nb.feature_count_

array([[35.,  3.,  1., ...,  0.,  0.,  0.],
       [27., 10.,  0., ...,  1.,  1.,  1.]])

- two rows show two classes i.e row 1 is for 5-star reviews and row 0 is for 1 star reviews.
- token 0 i.e 1st token.....it is found 27 times in 5-star review and 35 times in 1 star review

In [46]:
nb.feature_count_.shape

(2, 16867)

In [47]:
# number of times each token appears across all 5 star reviews
fivestar_token_count = nb.feature_count_[1, :]
fivestar_token_count

array([27., 10.,  0., ...,  1.,  1.,  1.])

In [48]:
onestar_token_count = nb.feature_count_[0, :]
onestar_token_count

array([35.,  3.,  1., ...,  0.,  0.,  0.])

In [49]:
# create a DataFrame of tokens with their separate ham and spam counts
tokens = pd.DataFrame({'token':X_train_tokens, '1-star':onestar_token_count, '5-star':fivestar_token_count}).set_index('token')

In [50]:
tokens.sample(5, random_state=2020)

1-star  5-star
token                     
stilll         0.0     1.0
steen          0.0     1.0
wah            0.0     1.0
flipstick      0.0     1.0
discordant     1.0     0.0

In [51]:
# add 1 to class counts to avoid dividing by 0
tokens['1-star'] = tokens['1-star'] + 1
tokens['5-star'] = tokens['5-star'] + 1
tokens.sample(5, random_state=2020)

1-star  5-star
token                     
stilll         1.0     2.0
steen          1.0     2.0
wah            1.0     2.0
flipstick      1.0     2.0
discordant     2.0     1.0

In [52]:
# Naive Bayes counts the number of observations in each class
nb.class_count_

array([ 563., 2501.])

In [53]:
# convert the class counts into frequencies
tokens['1-star'] = tokens['1-star'] / nb.class_count_[0]
tokens['5-star'] = tokens['5-star'] / nb.class_count_[1]
tokens.sample(5, random_state=2020)

1-star  5-star
token                       
stilll      0.001776  0.0008
steen       0.001776  0.0008
wah         0.001776  0.0008
flipstick   0.001776  0.0008
discordant  0.003552  0.0004

In [54]:
# calculate the ratio of reviews for positive review i.e 5 stars each token
tokens['review_ratio'] = tokens['5-star'] / tokens['1-star']
tokens.sample(5, random_state=2020)

1-star  5-star  review_ratio
token                                     
stilll      0.001776  0.0008      0.450220
steen       0.001776  0.0008      0.450220
wah         0.001776  0.0008      0.450220
flipstick   0.001776  0.0008      0.450220
discordant  0.003552  0.0004      0.112555

In [55]:
tokens.sort_values('review_ratio', ascending=False)

1-star    5-star  review_ratio
token                                           
fantastic       0.001776  0.071172     40.069572
perfect         0.003552  0.091963     25.887645
favorite        0.005329  0.131148     24.612022
yum             0.001776  0.024790     13.956817
art             0.001776  0.019992     11.255498
...                  ...       ...           ...
inedible        0.017762  0.000400      0.022511
unprofessional  0.019538  0.000400      0.020465
ignored         0.024867  0.000400      0.016079
refused         0.024867  0.000400      0.016079
staffperson     0.030195  0.000400      0.013242

[16867 rows x 3 columns]

### 10 tokens are the most predictive of 5-star reviews

In [56]:
tokens.sort_values('review_ratio', ascending=False).head(10)

1-star    5-star  review_ratio
token                                       
fantastic   0.001776  0.071172     40.069572
perfect     0.003552  0.091963     25.887645
favorite    0.005329  0.131148     24.612022
yum         0.001776  0.024790     13.956817
art         0.001776  0.019992     11.255498
view        0.001776  0.018393     10.355058
pasty       0.001776  0.015994      9.004398
organic     0.001776  0.015594      8.779288
mozzarella  0.001776  0.015194      8.554178
gem         0.001776  0.015194      8.554178

### 10 tokens are the most predictive of 1-star reviews

In [57]:
tokens.sort_values('review_ratio', ascending=False).tail(10)

# Or we can use
#tokens.sort_values('review_ratio', ascending=True).head(10)

1-star    5-star  review_ratio
token                                           
mistake         0.042629  0.001200      0.028139
gratuity        0.014210  0.000400      0.028139
fuse            0.014210  0.000400      0.028139
ugh             0.033748  0.000800      0.023696
awful           0.071048  0.001599      0.022511
inedible        0.017762  0.000400      0.022511
unprofessional  0.019538  0.000400      0.020465
ignored         0.024867  0.000400      0.016079
refused         0.024867  0.000400      0.016079
staffperson     0.030195  0.000400      0.013242

## Task 9 (Challenge)

Up to this point, we have framed this as a **binary classification problem** by only considering the 5-star and 1-star reviews. Now, let's repeat the model building process using all reviews, which makes this a **5-class classification problem**.

Here are the steps:

- Define X and y using the original DataFrame. (y should contain 5 different classes.)
- Split X and y into training and testing sets.
- Create document-term matrices using CountVectorizer.
- Calculate the testing accuracy of a Multinomial Naive Bayes model.
- Compare the testing accuracy with the null accuracy, and comment on the results.
- Print the confusion matrix, and comment on the results. (This [Stack Overflow answer](http://stackoverflow.com/a/30748053/1636598) explains how to read a multi-class confusion matrix.)
- Print the [classification report](http://scikit-learn.org/stable/modules/model_evaluation.html#classification-report), and comment on the results. If you are unfamiliar with the terminology it uses, research the terms, and then try to figure out how to calculate these metrics manually from the confusion matrix!

### a.Going back to original dataset

In [58]:
df.shape

(10000, 10)

In [59]:
df.head()

business_id        date               review_id  stars  \
0  9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1  ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
2  6oRAC4uyJCsJl1X0WZpVSA  2012-06-14  IESLBzqUCLdSzSqm0eCSxQ      4   
3  _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4  6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   

                                                text    type  \
0  My wife took me here on my birthday for breakf...  review   
1  I have no idea why some people give bad review...  review   
2  love the gyro plate. Rice is so good and I als...  review   
3  Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4  General Manager Scott Petello is a good egg!!!...  review   

                  user_id  cool  useful  funny  
0  rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1  0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
2  0hT2KtfLiobPvh6cDC8JQg     0       1      0  
3  uZetl9T0NcROGOyFfughhg     1       2      0  
4  vYmM4KTsC8ZfQBg-j5MWkw     0       0      0

In [60]:
df.stars.value_counts()

4    3526
5    3337
3    1461
2     927
1     749
Name: stars, dtype: int64

### b.Splitting data into X and y

Also train-test split

In [61]:
X=df.text
y=df.stars

In [62]:
print(X.shape)
print(y.shape)

(10000,)
(10000,)


In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=2020)
print(X_train.shape)
print(X_test.shape)

(7500,)
(2500,)


### c.document-term matrices using CountVectorizer.

In [64]:
X_train_dtm = vect.fit_transform(X_train)
X_train_dtm

<7500x25527 sparse matrix of type '<class 'numpy.int64'>'
	with 616754 stored elements in Compressed Sparse Row format>

In [65]:
X_train_dtm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [66]:
ngram=pd.DataFrame(X_train_dtm.toarray(), columns=vect.get_feature_names())
ngram.shape

(7500, 25527)

In [67]:
# only using transform , not fit
X_test_dtm = vect.transform(X_test)
X_test_dtm.shape

(2500, 25527)

### d.Building Model

In [68]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [69]:
%time nb.fit(X_train_dtm, y_train)

CPU times: user 14 ms, sys: 3.78 ms, total: 17.7 ms
Wall time: 11.2 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [70]:
y_pred_class = nb.predict(X_test_dtm)
y_pred_class[:5]

array([4, 3, 4, 4, 4])

### e.Model Results

#### null accuracy

In [74]:
y_test.value_counts()

4    905
5    825
3    372
2    222
1    176
Name: stars, dtype: int64

In [73]:
y_test.value_counts().head(1) / len(y_test)

4    0.362
Name: stars, dtype: float64

#### accuracy

In [71]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.4956

#### confusion matrix

In [72]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[ 52,  27,  15,  62,  20],
       [ 22,  23,  37, 121,  19],
       [  5,   8,  28, 294,  37],
       [  6,   2,  18, 658, 221],
       [  5,   0,   8, 334, 478]])

#### roc-auc

In [77]:
y_pred_prob = nb.predict_proba(X_test_dtm)
y_pred_prob[:1]

array([[1.79524898e-34, 1.31367150e-07, 1.40373636e-07, 9.99998942e-01,
        7.85889838e-07]])

In [78]:
y_pred_class[:1]

array([4])

#### classification report

In [75]:
# print the classification report
print(metrics.classification_report(y_test, y_pred_class))

              precision    recall  f1-score   support

           1       0.58      0.30      0.39       176
           2       0.38      0.10      0.16       222
           3       0.26      0.08      0.12       372
           4       0.45      0.73      0.55       905
           5       0.62      0.58      0.60       825

    accuracy                           0.50      2500
   macro avg       0.46      0.36      0.36      2500
weighted avg       0.48      0.50      0.46      2500



- Class 2 and 3 has low recall, meaning that the model has a hard time detecting the 2-star and 3-star.
- Class 1 has low recall, meaning that the model has a hard time detecting the 1-star reviews, but high precision, meaning that when the model predicts a review is 1-star, it's usually correct.
- Class 5 has high recall and precision, probably because 5-star reviews have polarized language, and because the model has a lot of observations to learn from. 